package com.rathercruel.translit.programmes;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.Timer;

/**
 *
 * @author rathercruel
 */

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     * @param windowTitle
     */
    
    private Timer timer;
    
    public GUI(String windowTitle) {
        initComponents();
        this.setTitle(windowTitle);
        
        // ! ВРЕМЕННЫЙ КОСТЫЛЬ
        timer = new Timer(100, e -> {
            convertUkrainianMethod();
            convertBelarusianMethod();
        });
        timer.start();
        ukrainianCheckBox.addItemListener(
            new ItemListener() {
              @Override
              public void itemStateChanged(ItemEvent e) {
                 ukrainianInput.setLineWrap( e.getStateChange() == ItemEvent.SELECTED );
                 ukrainianOutput.setLineWrap( e.getStateChange() == ItemEvent.SELECTED );
              }
        } );
        
        belarusianCheckBox.addItemListener(
            new ItemListener() {
              @Override
              public void itemStateChanged(ItemEvent e) {
                 belarusianInput.setLineWrap( e.getStateChange() == ItemEvent.SELECTED );
                 belarusianOutput.setLineWrap( e.getStateChange() == ItemEvent.SELECTED );
              }
        } );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiTabs = new javax.swing.JTabbedPane();
        ukrainian = new javax.swing.JPanel();
        ukrainianTitle = new javax.swing.JLabel();
        ukrainianInputScrollPane = new javax.swing.JScrollPane();
        ukrainianInput = new javax.swing.JTextArea();
        ukrainianOutputScrollPane = new javax.swing.JScrollPane();
        ukrainianOutput = new javax.swing.JTextArea();
        ukrainianCopyButton = new javax.swing.JButton();
        ukrainianComboBox = new javax.swing.JComboBox<>();
        ukrainianCheckBox = new javax.swing.JCheckBox();
        belarusian = new javax.swing.JPanel();
        belarusianTitle = new javax.swing.JLabel();
        belarusianInputScrollPane = new javax.swing.JScrollPane();
        belarusianInput = new javax.swing.JTextArea();
        belarusianOutputScrollPane = new javax.swing.JScrollPane();
        belarusianOutput = new javax.swing.JTextArea();
        belarusianCopyButton = new javax.swing.JButton();
        belarusianComboBox = new javax.swing.JComboBox<>();
        belarusianCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        guiTabs.setMinimumSize(new java.awt.Dimension(78, 372));
        guiTabs.setPreferredSize(new java.awt.Dimension(838, 369));

        ukrainianTitle.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        ukrainianTitle.setText("Perekłady swój text tut:");
        ukrainianTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ukrainianInput.setColumns(20);
        ukrainianInput.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        ukrainianInput.setRows(5);
        ukrainianInputScrollPane.setViewportView(ukrainianInput);

        ukrainianOutput.setEditable(false);
        ukrainianOutput.setColumns(20);
        ukrainianOutput.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        ukrainianOutput.setRows(5);
        ukrainianOutputScrollPane.setViewportView(ukrainianOutput);
        ukrainianOutput.getAccessibleContext().setAccessibleName("ukrainianTranslit");

        ukrainianCopyButton.setText("Copy");
        ukrainianCopyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukrainianCopyButtonActionPerformed(evt);
            }
        });

        ukrainianComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abecadło", "Jirečkivka", "Psevdo-Jirečkivka", "Official KMU 2010", "Na Chasi 2017", "Czech Translit", "ТКПН combo", "ТКПН diac", "ТКПН intl", "ISO9" }));
        ukrainianComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukrainianComboBoxActionPerformed(evt);
            }
        });

        ukrainianCheckBox.setText("Word Warp");
        ukrainianCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukrainianCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ukrainianLayout = new javax.swing.GroupLayout(ukrainian);
        ukrainian.setLayout(ukrainianLayout);
        ukrainianLayout.setHorizontalGroup(
            ukrainianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ukrainianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ukrainianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ukrainianLayout.createSequentialGroup()
                        .addComponent(ukrainianTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ukrainianLayout.createSequentialGroup()
                        .addGroup(ukrainianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ukrainianLayout.createSequentialGroup()
                                .addComponent(ukrainianCopyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ukrainianCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ukrainianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ukrainianOutputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
                            .addComponent(ukrainianInputScrollPane))
                        .addContainerGap())))
        );
        ukrainianLayout.setVerticalGroup(
            ukrainianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ukrainianLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ukrainianTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ukrainianInputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ukrainianOutputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ukrainianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ukrainianCopyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ukrainianCheckBox)
                    .addComponent(ukrainianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        guiTabs.addTab("Ukrajinśka", ukrainian);

        belarusianTitle.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        belarusianTitle.setText("Pierakladzicie svoj text tut:");
        belarusianTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        belarusianInput.setColumns(20);
        belarusianInput.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        belarusianInput.setRows(5);
        belarusianInputScrollPane.setViewportView(belarusianInput);

        belarusianOutput.setEditable(false);
        belarusianOutput.setColumns(20);
        belarusianOutput.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        belarusianOutput.setRows(5);
        belarusianOutputScrollPane.setViewportView(belarusianOutput);

        belarusianCopyButton.setText("Copy");
        belarusianCopyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belarusianCopyButtonActionPerformed(evt);
            }
        });

        belarusianComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aficyjnaja", "Tradycyjnaja" }));

        belarusianCheckBox.setText("Word Warp");
        belarusianCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belarusianCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout belarusianLayout = new javax.swing.GroupLayout(belarusian);
        belarusian.setLayout(belarusianLayout);
        belarusianLayout.setHorizontalGroup(
            belarusianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(belarusianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(belarusianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(belarusianLayout.createSequentialGroup()
                        .addComponent(belarusianTitle)
                        .addGap(0, 642, Short.MAX_VALUE))
                    .addGroup(belarusianLayout.createSequentialGroup()
                        .addGroup(belarusianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(belarusianLayout.createSequentialGroup()
                                .addComponent(belarusianCopyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(belarusianCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(belarusianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(belarusianOutputScrollPane)
                            .addComponent(belarusianInputScrollPane))
                        .addContainerGap())))
        );
        belarusianLayout.setVerticalGroup(
            belarusianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(belarusianLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(belarusianTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(belarusianInputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(belarusianOutputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(belarusianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(belarusianCopyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(belarusianCheckBox)
                    .addComponent(belarusianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        guiTabs.addTab("Biełaruskaja", belarusian);

        getContentPane().add(guiTabs, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ukrainianCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukrainianCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ukrainianCheckBoxActionPerformed

    private void ukrainianCopyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukrainianCopyButtonActionPerformed
        // TODO add your handling code here:
        String userOutput = ukrainianOutput.getText();
        Clipboard clip = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection strsel = new StringSelection(userOutput);
        clip.setContents(strsel, strsel);
    }//GEN-LAST:event_ukrainianCopyButtonActionPerformed

    private void belarusianCopyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belarusianCopyButtonActionPerformed
        // TODO add your handling code here:
        String userOutput = belarusianOutput.getText();
        Clipboard clip = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection strsel = new StringSelection(userOutput);
        clip.setContents(strsel, strsel);
    }//GEN-LAST:event_belarusianCopyButtonActionPerformed

    private void belarusianCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belarusianCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_belarusianCheckBoxActionPerformed

    private void ukrainianComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukrainianComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ukrainianComboBoxActionPerformed
    
    public void convertUkrainianMethod() {
        String userTextAreaInput = ukrainianInput.getText();
        String itemValue = ukrainianComboBox.getSelectedItem().toString();
        // Jirečkivka, Official KMU 2010, ТКПН combo, ТКПН diac, ТКПН intl, ISO9
        switch (itemValue) {
            case "Jirečkivka" -> {
                Jireckivka jireckivka = new Jireckivka(userTextAreaInput);
                ukrainianOutput.setText(jireckivka.getOutput());
            }
            case "Psevdo-Jirečkivka" -> {
                PsevdoJireckivka psevdoJireckivka = new PsevdoJireckivka(userTextAreaInput);
                ukrainianOutput.setText(psevdoJireckivka.getOutput());
            }
            case "Abecadło" -> {
                Abecadlo abecadlo = new Abecadlo(userTextAreaInput);
                ukrainianOutput.setText(abecadlo.getOutput());
            }
            case "ТКПН diac" -> {
                TkpnDiac tkpnDiac = new TkpnDiac(userTextAreaInput);
                ukrainianOutput.setText(tkpnDiac.getOutput());
            }
            case "ТКПН combo" -> {
                TkpnCombo tkpnCombo = new TkpnCombo(userTextAreaInput);
                ukrainianOutput.setText(tkpnCombo.getOutput());
            }
            case "ТКПН intl" -> {
                TkpnIntl tkpnIntl = new TkpnIntl(userTextAreaInput);
                ukrainianOutput.setText(tkpnIntl.getOutput());
            }
            case "Na Chasi 2017" -> {
                NaChasi naChasi = new NaChasi(userTextAreaInput);
                ukrainianOutput.setText(naChasi.getOutput());
            }
            case "Official KMU 2010" -> {
                OfficialKMU2010 officialKMU2010 = new OfficialKMU2010(userTextAreaInput);
                ukrainianOutput.setText(officialKMU2010.getOutput());
            }
            case "Czech Translit" -> {
                CzechTranslit czechTranslit = new CzechTranslit(userTextAreaInput);
                ukrainianOutput.setText(czechTranslit.getOutput());
            }
            case "ISO9" -> {
                Iso9 iso9 = new Iso9(userTextAreaInput);
                ukrainianOutput.setText(iso9.getOutput());
            }
            default -> {
                Abecadlo abecadlo = new Abecadlo(userTextAreaInput);
                ukrainianOutput.setText(abecadlo.getOutput());
            }
        }
    }
    
    public void convertBelarusianMethod() {
        String userTextAreaInput = belarusianInput.getText();
        String itemValue = belarusianComboBox.getSelectedItem().toString();

        switch (itemValue) {
            case "Aficyjnaja" -> {
                Belarusian.alphabet.put("л", "l");
                Belarusian.softLetters.put("л", "ĺ");
                Belarusian belarusian = new Belarusian(userTextAreaInput);
                belarusianOutput.setText(belarusian.getOutput());
            }
            case "Tradycyjnaja" -> {
                Belarusian.alphabet.put("л", "ł");
                Belarusian.softLetters.put("л", "l");
                Belarusian belarusian = new Belarusian(userTextAreaInput);
                belarusianOutput.setText(belarusian.getOutput());
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel belarusian;
    private javax.swing.JCheckBox belarusianCheckBox;
    private javax.swing.JComboBox<String> belarusianComboBox;
    private javax.swing.JButton belarusianCopyButton;
    private javax.swing.JTextArea belarusianInput;
    private javax.swing.JScrollPane belarusianInputScrollPane;
    private javax.swing.JTextArea belarusianOutput;
    private javax.swing.JScrollPane belarusianOutputScrollPane;
    private javax.swing.JLabel belarusianTitle;
    private javax.swing.JTabbedPane guiTabs;
    private javax.swing.JPanel ukrainian;
    private javax.swing.JCheckBox ukrainianCheckBox;
    private javax.swing.JComboBox<String> ukrainianComboBox;
    private javax.swing.JButton ukrainianCopyButton;
    private javax.swing.JTextArea ukrainianInput;
    private javax.swing.JScrollPane ukrainianInputScrollPane;
    private javax.swing.JTextArea ukrainianOutput;
    private javax.swing.JScrollPane ukrainianOutputScrollPane;
    private javax.swing.JLabel ukrainianTitle;
    // End of variables declaration//GEN-END:variables
}
